#!/bin/bash

PACKAGES="glib-2.0 gobject-2.0 elementary"
CFLAGS="`pkg-config --cflags ${PACKAGES}`"
LIBS="`pkg-config --libs ${PACKAGES}`"
SOURCES="main.c test_mainwin.c"

edje_cc test.edc test.edj &&
gcc -Wall -DPACKAGE=\"mokojeweled\" -DVERSION=\"0.1\" ${CFLAGS} ${LIBS} -o mokojeweled ${SOURCES} &&
echo "Compiled." &&
./mokojeweled
